apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  clusterIP: None
  selector:
    app: fine-tune
  ports:
    - protocol: TCP
      port: 29500  # Port for DDP communication
      targetPort: 29500
