apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-labeler-binding
subjects:
- kind: ServiceAccount
  name: fine-tune-sa
  namespace: finetune
roleRef:
  kind: Role
  name: pod-labeler
  apiGroup: rbac.authorization.k8s.io
